services:
  mysqldb:
    container_name: mysqldb-service
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpachat
    volumes:
      - /home/mysql/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


  spring_app:
    #    image: timesheet:latest

    build:
      context: .
      dockerfile: Dockerfile

    container_name: timesheetContainer
    restart: on-failure
    ports:
      - 9096:9096
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb-service:3306/tpachat?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=9096