apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort  # Use NodePort instead of LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001  # Choose a port between 30000-32767
  selector:
    app: mysqldb
